Update readme to join as a new validator
yetanotherco/aligned_layer_tendermint pull request #29
Opened 2024-03-12 19:09 UTC by GabrielSac

Added step-by-step guide to set up new node and join as validator.

2024-03-12 19:29 UTC, ManuelBilbao requested changes

2024-03-12 19:29 UTC, ManuelBilbao commented on README.md
> +1.
Here I'd explain what does this step do. Something like "Get the code and build the app"

2024-03-12 19:29 UTC, ManuelBilbao commented on README.md
> +```
Maybe we could recommend here to check if `~/go/bin` is in PATH, if the command fail

2024-03-12 19:29 UTC, ManuelBilbao commented on README.md
> +alignedlayerd init <your-node-name > --chain-id alignedlayerd
Don't leave a space before `>`, it seems like you are redirecting de output.
Also, the ChainID is without the final _d_
```suggestion
alignedlayerd init <your-node-name> --chain-id alignedlayer
```

2024-03-12 19:29 UTC, ManuelBilbao commented on README.md
> +4. You now need to download the blockchain genesis file and replace the one which was automatically generated for you:
Leave an extra space so it does the break line
```suggestion
If you have already run this command, you can use the -o flag to overwrite previously generated files. 

4. You now need to download the blockchain genesis file and replace the one which was automatically generated for you:
```

2024-03-12 19:29 UTC, ManuelBilbao commented on README.md
> +curl admin@blockchain-1:26657/genesis | jq '.result.genesis' > ~/.alignedlayer/config/genesis.json
Should this information (`admin@blockchain-1`) be here? We should ask if it's correct or put a placeholder

2024-03-12 19:29 UTC, ManuelBilbao commented on README.md
> +cd aligned_layer_tendermint
This line is not necessary, as the command is available anywhere

2024-03-12 19:29 UTC, ManuelBilbao commented on README.md
> +alignedlayerd keys add <your-validator >
```suggestion
alignedlayerd keys add <your-validator>
```

2024-03-12 19:29 UTC, ManuelBilbao commented on README.md
> +You'll be encouraged to save a moniker in case you need to recover your account.
I think you meant to say mnemonic here
```suggestion
You'll be encouraged to save a mnemonic in case you need to recover your account. 
```

2024-03-12 19:29 UTC, ManuelBilbao commented on README.md
> +Afterwards, you need to request funds to the administrator.
Leave an extra space so it does the break line
```suggestion

Afterwards, you need to request funds to the administrator. 
```

2024-03-12 19:29 UTC, ManuelBilbao commented on README.md
> +alignedlayerd tx staking create-validator validator.json --from <your-node-address > --node tcp://blockchain-1:26656
The `from` flag should receive the key name
```suggestion
alignedlayerd tx staking create-validator validator.json --from <your-validator> --node tcp://blockchain-1:26656
```

2024-03-12 19:29 UTC, ManuelBilbao commented on README.md
> +	"pubkey": "your-validator-address",
I think we need to put an example or some way to mention that this field must be in format `{"@type": "...", "key": "..."}`

2024-03-12 19:42 UTC, ManuelBilbao commented on README.md
> +persistent_peers = "COMPLETEHERE@blockchain-1:26656"
Here we can change `COMPLETEHERE` with the result of this command: `curl -s blockchain-1:26657/status | jq -r '.result.node_info.id'`

2024-03-12 20:07 UTC, ManuelBilbao requested changes

2024-03-12 20:07 UTC, ManuelBilbao commented on README.md
> +persistent_peers = "$(curl -s blockchain-1:26657/status | jq -r '.result.node_info.id')@blockchain-1:26656"
I think this isn't going to work. The command should be run previously and put the output here

2024-03-12 20:07 UTC, ManuelBilbao commented on README.md
We need to add `jq` as a requirement.

2024-03-12 20:12 UTC, ManuelBilbao requested changes

2024-03-12 20:12 UTC, ManuelBilbao commented on README.md
> +3. To create the node, run
```suggestion

3. To create the node, run
```

2024-03-12 20:12 UTC, ManuelBilbao commented on README.md
> +alignedlayerd --help
```suggestion
alignedlayerd version
```

2024-03-12 20:12 UTC, ManuelBilbao commented on README.md
> +You may need to add ~/go/bin to PATH.
Remove this since output is hardcoded on build

2024-03-12 20:12 UTC, ManuelBilbao commented on README.md
> +5. Open the config.toml file available in $HOME/.alignedlayer/config. Add the following address to the [p2p] seeds and persistent_peers:
Simplify this removing the "Open..."

2024-03-12 20:39 UTC, GabrielSac reviewed
LGTM

2024-03-12 21:36 UTC, fborello-lambda approved these changes

2024-03-12 22:14 UTC, tomyrd requested changes

2024-03-12 22:14 UTC, tomyrd commented on README.md
> +alignedlayerd tendermint show-validator
This step should appear sooner. It's used for the validator.json.

2024-03-12 22:14 UTC, tomyrd commented on README.md
> +alignedlayerd tx staking create-validator validator.json --from <your-validator-address> --node tcp://blockchain-1:26656
It's not clear what `your-validator-address` (i first thought it was the public key)

2024-03-12 22:14 UTC, tomyrd commented on README.md
> +alignedlayerd tx staking create-validator validator.json --from <your-validator-address> --node tcp://blockchain-1:26656
I can't finish the steps, i get the error `post failed: Post "http://blockchain-1:26656": EOF`. I think it's because it's missing the step where the user gets tokens.

2024-03-13 12:09 UTC, GabrielSac commented on README.md
> +```
Good idea!

2024-03-13 12:16 UTC, GabrielSac commented on README.md
> +```
I agree. I'll delete it, we can add info about this later on.

2024-03-13 16:25 UTC, JulianGCalderon requested changes
This PR shouldn't change openapi.yml as it does not change code. It also has merging conflicts, se we can checkout that file from main to avoid them.

2024-03-13 16:25 UTC, JulianGCalderon commented on README.md
> +```
I'd move this to the top as the primary solution, as someone following the tutorial will probably run step by step without looking ahead, although this is easier.

2024-03-13 16:50 UTC, JulianGCalderon submitted a review, later dismissed
LGTM

2024-03-14 12:41 UTC, JulianGCalderon submitted a review, later dismissed
LGTM

2024-03-14 13:03 UTC, tomyrd requested changes

2024-03-14 13:03 UTC, tomyrd commented on setup_validator.sh
> +	"amount": "'$STAKING_AMOUNT'stake",
The token name should be a variable. I think "stake" is just the name we are using for testing purposes.

2024-03-14 13:03 UTC, tomyrd commented on README.md
> +To set up a validator node, you can either run the provided script setup_validator.sh, or manually run the step by step instructions (see below). The script receives two command line parameters: the
We should add an example of how to run `setup_validator.sh`

2024-03-14 14:00 UTC, tomyrd approved these changes
LGTM

2024-03-14 14:10 UTC, JulianGCalderon approved these changes
LGTM

2024-03-14 14:10 UTC, merged