docker: add docker scripts for single node validator
yetanotherco/aligned_layer_tendermint pull request #82
Opened 2024-03-20 12:53 UTC by d-roak

2024-03-20 16:37 UTC, JulianGCalderon requested changes
The docker-compose works as intended, but i noticed that the create-validator transaction is sent right after the node is setup. 

The node won't be able to validate blocks until it has finished syncing up with the blockchain, which means that (if the blockchain is large enough) it could be slashed even before starting to validate.

Is there a way to wait for the node to catch-up before sending the create-validator transaction?

2024-03-20 16:37 UTC, JulianGCalderon commented on docker/scripts/validator.entrypoint.sh
> +    "security": "me+aligned@droak.sh"
We should leave an empty website and security by default.

2024-03-20 17:43 UTC, d-roak commented on docker/scripts/validator.entrypoint.sh
> +    "security": "me+aligned@droak.sh"
ohhh mb, on that, it was extracted from my node config

2024-03-20 18:16 UTC, ManuelBilbao commented
There's an endpoint which we can use for checking if syncing is complete: `localhost:26657/status`.

Maybe we can add something like this before the `create-validator` order:
```sh
while [ $(curl -s localhost:26657/status |  jq '.result.sync_info.catching_up') == "true" ]
do
    sleep 1
done
```

2024-03-20 19:03 UTC, tomyrd requested changes

2024-03-20 19:07 UTC, tomyrd requested changes

2024-03-20 19:07 UTC, tomyrd commented on multi_node_setup.sh
> -    fi
`else` referenced in [this comment](https://github.com/yetanotherco/aligned_layer_tendermint/pull/82#discussion_r1532638687).

2024-03-20 19:45 UTC, ManuelBilbao requested changes
If you stop the container and then start it again, the `node-setup` and `validator-setup` are run again, generating a new key with different address, thus generating another validator

2024-03-21 06:59 UTC, d-roak commented on multi_node_setup.sh
> -    fi
in the case `i=1` u have `cp prod-sim/$1/config/genesis.json prod-sim/$1/config/genesis.json` that is doing nothing. Same applies on the other scenario

2024-03-21 07:01 UTC, d-roak commented on docker/scripts/validator.entrypoint.sh
> +    "security": "me+aligned@droak.sh"
fixed in https://github.com/yetanotherco/aligned_layer_tendermint/pull/82/commits/6819e224238fd907c40e2e1a792ad311e4f47903

2024-03-21 07:24 UTC, d-roak commented
> The node won't be able to validate blocks until it has finished syncing up with the blockchain, which means that (if the blockchain is large enough) it could be slashed even before starting to validate.

Not sure how are cosmos chains handle status, but @ManuelBilbao suggestion should work to fix it

> If you stop the container and then start it again, the node-setup and validator-setup are run again, generating a new key with different address, thus generating another validator

True. A possible alternative is to go with `NODE_NAME=name docker compose -f docker/compose/validator.docker-compose.yml up validator-runner` (and remove the depends_on). To make it easier for operators, you can wrap it in the `Makefile` or a bash script

I opened this PR with what I had on my side to make it work for my specific environment and generic enough for it to work everywhere else. I don't intend to make it super reliable and fine-tuned for generic use cases. So you can either:
- work on top of it (only available for maintainers)
- merge it and work from there
- create a new PR with whatever you find useful and close this one 🫡

cc @JulianGCalderon @ManuelBilbao @tomyrd @MauroToscano

2024-03-21 07:28 UTC, d-roak commented on multi_node_setup.sh
> -    fi
![image](https://github.com/yetanotherco/aligned_layer_tendermint/assets/5263301/e7c5789f-787e-4f3d-bf71-dfee327ead6f)

this is the message that you get on those `else` cases

2024-03-21 12:50 UTC, tomyrd commented on multi_node_setup.sh
> -    fi
Ohh you are right. In the case `i=1` this else makes it fail. In other scenarios though that copies goes from the last to the first. Thanks for the help.

2024-03-21 16:20 UTC, MauroToscano commented
We can merge this and keep working on it

2024-03-21 17:40 UTC, ManuelBilbao approved these changes

2024-03-21 17:50 UTC, JulianGCalderon approved these changes
LGTM

2024-03-21 17:51 UTC, tomyrd approved these changes
LGTM

2024-03-21 17:54 UTC, merged