Fix the steps in README to create a new node
yetanotherco/aligned_layer_tendermint pull request #89
Opened 2024-03-21 15:30 UTC by tomyrd

The old steps in the README only connects the new node to one server. This makes it so that if the server fails then the node disconnects. The steps should explain how to connect to multiple servers from the start.

2024-03-22 17:31 UTC, MauroToscano submitted a review, later dismissed

2024-03-22 20:16 UTC, ManuelBilbao commented on README.md
> +curl -s <public_node_IP>:26657/genesis | jq '.result.genesis' > ~/.alignedlayer/config/genesis.json
Is it a good idea to change this? We put that to simplify and accelerate the process, so the user don't have to edit the commands, only setup an envvar

2024-03-22 20:16 UTC, ManuelBilbao commented on README.md
> +curl -s <node_IP>:26657/status | jq -r '.result.node_info.id'
Same here

2024-03-22 20:16 UTC, ManuelBilbao commented on README.md
> +alignedlayerd config set config p2p.persistent_peers "<init_node_list>" --skip-validate
And here

2024-03-25 15:16 UTC, tomyrd commented on README.md
> +curl -s <public_node_IP>:26657/genesis | jq '.result.genesis' > ~/.alignedlayer/config/genesis.json
The problem is that now the user doesn't connect to one node. They connect to multiple nodes so the envvar becomes obsolete. We discussed changing de variable to be a list of ips separated by commas but that would require a script to do the work, which we don't want because this are the manual steps.

2024-03-25 15:32 UTC, ManuelBilbao requested changes

2024-03-25 15:32 UTC, ManuelBilbao commented on README.md
> +<node1_IP>@<node1_ID>:26656,<node2_IP>@<node2_ID>:26656,...
```suggestion
<node1_ID>@<node1_IP>:26656,<node2_ID>@<node2_IP>:26656,...
```
This must be `node_ID@node_IP:26656`.

2024-03-25 15:56 UTC, ManuelBilbao commented on README.md
> +alignedlayerd config set config p2p.persistent_peers "<init_node_list>" --skip-validate
We can obtain the `<init_node_list>` with one of this.
1. Assigning to an envvar `ids`: `export ids=""; for ip in $(echo $PEER_ADDR | sed 's/,/ /g'); do export ids="$ids$(curl -s $ip:26657/status | jq -r '.result.node_info.id')@$ip:26656,"; done`
2. Echoing: `for ip in $(echo $PEER_ADDR | sed 's/,/ /g'); do echo -n "$(curl -s $ip:26657/status | jq -r '.result.node_info.id')@$ip:26656,"; done`

I don't know if the trailing comma would generate problem. In that case, it can be removed with:
1. `export ids=${ids%?}`
2. Pipelining the command with: `rev | cut -c 2- | rev`

We may discuss if it's worth the spaghetti in exchange of a copy-paste command

2024-03-25 18:23 UTC, tomyrd commented on README.md
> +curl -s <public_node_IP>:26657/genesis | jq '.result.genesis' > ~/.alignedlayer/config/genesis.json
Done.

2024-03-25 18:24 UTC, tomyrd commented on README.md
> +curl -s <node_IP>:26657/status | jq -r '.result.node_info.id'
This command is not needed anymore.

2024-03-25 18:26 UTC, tomyrd commented on README.md
> +alignedlayerd config set config p2p.persistent_peers "<init_node_list>" --skip-validate
Done. Thanks for the suggestion. I used the first option and added the command to remove the trailing comma.

2024-03-25 18:26 UTC, tomyrd commented on README.md
> +<node1_IP>@<node1_ID>:26656,<node2_IP>@<node2_ID>:26656,...
Done.

2024-03-25 18:57 UTC, ManuelBilbao approved these changes
LGTM

2024-03-25 19:02 UTC, JulianGCalderon approved these changes
LGTM

2024-03-25 19:02 UTC, merged