Add Multiple Node Setup Using Docker
yetanotherco/aligned_layer_tendermint pull request #9
Opened 2024-03-08 20:59 UTC by tomyrd

Added script that builds a local chain using docker compose with setup instructions in the README.

2024-03-08 21:01 UTC, jotabulacios approved these changes
LGTM

2024-03-08 21:40 UTC, ManuelBilbao requested changes

2024-03-08 21:40 UTC, ManuelBilbao commented on multi_node_setup.sh
> +done
New line is missing

2024-03-08 21:40 UTC, ManuelBilbao commented on README.md
> +## Setting Up Multiple Nodes Using Docker
```suggestion
## Setting up multiple local nodes using Docker
```
I'd add that nodes are local

2024-03-08 21:40 UTC, ManuelBilbao commented on README.md
> +```
What does this script does? I think we need to add more detail on this step, as it's not obvious.
Also, maybe an example command would be good, e.g. `bash multi_node_setup.sh node0 node1 node2`

2024-03-08 21:40 UTC, ManuelBilbao commented on README.md
> +```
This could be any node or only the first? If any, I'd say something like this
```suggestion
You can verify that it works by running (replacing `<node_name>` by the name of one of the nodes put in the bash script):
```sh
docker run --rm -it --network lambchain_net-public lambchaind_i status --node "tcp://<node_name>:26657"
```
```

2024-03-08 21:40 UTC, ManuelBilbao commented on README.md
> +## Setting Up Multiple Nodes Using Docker
Also, make a short description of what this steps are going to do

2024-03-08 21:47 UTC, JulianGCalderon requested changes
I wrote a few comments we can discuss

2024-03-08 21:47 UTC, JulianGCalderon commented on multi_node_setup.sh
> +done
Add trailing newline at end of file.

2024-03-08 21:47 UTC, JulianGCalderon commented on README.md
> +```
I'd add a minor description of the bash script. The meaning of the node names, the expected output (what files are created), etc.

2024-03-08 21:47 UTC, JulianGCalderon commented on Dockerfile
I think is better to have multistage build for docker, we can add an issue to deal with it later.

2024-03-08 21:47 UTC, JulianGCalderon commented on README.md
> +```
Maybe we should have a Makefile that calls this script? Something like simd has: `make testnet`.

2024-03-08 21:47 UTC, JulianGCalderon commented on README.md
> +```
We could add a description about what containers does the docker-compose run, or what port it exports (and from which node).

2024-03-08 21:47 UTC, JulianGCalderon commented on multi_node_setup.sh
> +done
The docker compose should be written in the prod-sim directory so it does not conflict with any future docker-compose.yml.

if we save it in that directory, there is no need to ignore it in .gitignore.

2024-03-08 21:47 UTC, JulianGCalderon commented on README.md
> +Build docker image:
nitpick: To keep consistency with the rest of the README, I think we should leave blank lines around codeblocks.

2024-03-11 21:00 UTC, tomyrd commented on README.md
> +```
It has to be the first node, its the only one with the open port

2024-03-11 21:54 UTC, tomyrd commented on multi_node_setup.sh
> +done
Solved

2024-03-11 21:54 UTC, tomyrd commented on README.md
> +## Setting Up Multiple Nodes Using Docker
Solved

2024-03-11 21:54 UTC, tomyrd commented on README.md
> +```
Solved

2024-03-11 21:55 UTC, tomyrd commented on README.md
> +```
Solved. Added a small description of the exposed ports.

2024-03-11 21:55 UTC, tomyrd commented on README.md
> +```
Solved

2024-03-12 15:42 UTC, JulianGCalderon approved these changes
LGTM

2024-03-12 16:46 UTC, tomyrd commented on multi_node_setup.sh
> +done
Solved

2024-03-12 16:47 UTC, jotabulacios approved these changes
LGTM

2024-03-12 16:47 UTC, JulianGCalderon approved these changes
LGTM

2024-03-12 18:15 UTC, ManuelBilbao approved these changes

2024-03-12 18:15 UTC, merged