Improve Docker scripts
yetanotherco/aligned_layer_tendermint pull request #92
Opened 2024-03-21 19:28 UTC by ManuelBilbao

Fix and improve Docker initialization of the project

2024-03-22 20:31 UTC, JulianGCalderon requested changes

2024-03-22 20:31 UTC, JulianGCalderon commented on docker/scripts/node.entrypoint.sh
> +$CHAIN_BINARY config set config rpc.laddr "tcp://0.0.0.0:26657" --skip-validate
Minimum gas prices should be already set by app config

2024-03-22 20:41 UTC, ManuelBilbao commented on docker/scripts/node.entrypoint.sh
> +$CHAIN_BINARY config set config rpc.laddr "tcp://0.0.0.0:26657" --skip-validate
Done

2024-03-22 20:47 UTC, JulianGCalderon approved these changes
LGTM

2024-03-25 18:07 UTC, fborello-lambda submitted a review, later dismissed

2024-03-25 19:03 UTC, MauroToscano approved these changes

2024-03-25 19:51 UTC, JulianGCalderon approved these changes
LGTM

2024-03-25 21:31 UTC, tomyrd approved these changes
LGTM

2024-03-25 21:31 UTC, merged